# Generated by Django 4.1.5 on 2023-01-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billshareapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='split_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
    ]
