# Generated by Django 4.1.5 on 2023-02-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billshareapi', '0002_authuser_rename_date_payment_date_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='uid',
            field=models.CharField(default='', max_length=55),
        ),
    ]
