# Generated by Django 4.1.5 on 2023-01-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billshareapi', '0003_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='bill_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='split_amount',
            field=models.JSONField(),
        ),
    ]
