# Generated by Django 4.1.5 on 2023-01-28 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billshareapi', '0005_remove_people_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='bill_id',
        ),
    ]
