# Generated by Django 4.1.5 on 2023-01-30 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billshareapi', '0007_paymenttype_remove_payment_uid_remove_people_bill_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='bill',
        ),
        migrations.AddField(
            model_name='people',
            name='bill_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billshareapi.bill'),
        ),
    ]
