# Generated by Django 4.1.5 on 2023-01-30 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billshareapi', '0008_remove_people_bill_people_bill_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='bill_id',
            new_name='bill',
        ),
    ]
