# Generated by Django 4.1.5 on 2023-02-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billshareapi', '0010_alter_payment_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='total',
            new_name='amount_paid',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='date_paid',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='name',
            new_name='label',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(max_length=55),
        ),
        migrations.DeleteModel(
            name='PaymentType',
        ),
    ]
